Fixing training with ctc loss
castorini/howl pull request #47
Opened 2021-02-10 01:14 UTC by ljj7975

2021-02-11 01:11 UTC, edwinzhng approved these changes

2021-02-11 05:04 UTC, daemon requested changes

2021-02-11 05:04 UTC, daemon commented on howl/data/tokenize.py
> +        transcript = " " + transcript + " "
Do `f' {transcript} '` instead.

2021-02-11 05:04 UTC, daemon commented on howl/data/tokenize.py
> +        transcript = " " + transcript + " "
And does the codebase use single quotes or double quotes? I would keep the style consistent.

2021-02-11 05:04 UTC, daemon commented on howl/model/inference.py
> +        scores = self.model(self.zmuv(self.std(audio_data.unsqueeze(0))), None) # [num_frames x 1 (batch size) x num_labels]
Two spaces between the ) and #.

2021-02-11 05:04 UTC, daemon commented on howl/run/train.py
> +            total_loss += loss
You want to do
```
with torch.no_grad():
  total_loss += loss
```
to avoid accumulating the loss gradient.

2021-02-15 02:46 UTC, daemon commented
Can you fix the conflicts then we can merge?

2021-02-15 22:29 UTC, ljj7975 commented
@daemon I have found that demo.py does not work with ctc version. 
I will fix it in a separate MR

2021-02-15 22:29 UTC, merged